import { Router } from 'express';
import healthRouter from './health';
import authRouter from './auth';
import brandsRouter from './brands';
import categoriesRouter from './categories';
import productsRouter from './products';
import suppliersRouter from './suppliers';
import stockRouter from './stock';
import customersRouter from './customers';
import techniciansRouter from './technicians';
import defectsRouter from './defects';
import serviceCatalogRouter from './service-catalog';
import serviceOrdersRouter from './service-orders';
import couponsRouter from './coupons';
import cartRouter from './cart';
import ordersRouter from './orders';
import favoritesRouter from './favorites';
import addressesRouter from './addresses';
import couponPreviewRouter from './coupon-preview';
import bannersRouter from './banners';
import storeSettingsRouter from './store-settings';
import usersRouter from './users';
import logsRouter from './logs';
import dashboardRouter from './dashboard';
import paymentsRouter from './payments';
import warrantiesRouter from './warranties';
import warrantyPoliciesRouter from './warranty-policies';
import docsRouter from './docs';
import reportsRouter from './reports';
import accountsReceivableRouter from './accounts-receivable';

const router: Router = Router();

router.use('/health', healthRouter);
router.use('/docs', docsRouter);
router.use('/auth', authRouter);
router.use('/brands', brandsRouter);
router.use('/categories', categoriesRouter);
router.use('/products', productsRouter);
router.use('/suppliers', suppliersRouter);
router.use('/stock', stockRouter);
router.use('/customers', customersRouter);
router.use('/technicians', techniciansRouter);
router.use('/defects', defectsRouter);
router.use('/service-catalog', serviceCatalogRouter);
router.use('/service-orders', serviceOrdersRouter);
router.use('/coupons', couponsRouter);
router.use('/cart', cartRouter);
router.use('/orders', ordersRouter);
router.use('/favorites', favoritesRouter);
router.use('/addresses', addressesRouter);
router.use('/coupon-preview', couponPreviewRouter);
router.use('/banners', bannersRouter);
router.use('/store-settings', storeSettingsRouter);
router.use('/users', usersRouter);
router.use('/logs', logsRouter);
router.use('/dashboard', dashboardRouter);
router.use('/payments', paymentsRouter);
router.use('/warranties', warrantiesRouter);
router.use('/warranty-policies', warrantyPoliciesRouter);
router.use('/reports', reportsRouter);
router.use('/accounts-receivable', accountsReceivableRouter);

export default router;
